[package]
name = "wayland_overlay_media_viewer"
version = "0.1.0"
edition = "2024"

[dependencies]

# TODO remove unneded features
bevy = "0.19"
clap = { version = "4.5", features = ["derive"] }

raw-window-handle = "0.6.2"
wgpu = { version = "29.0.3" }

# wayland
wayland-backend = { version = "0.3.11", features = ["client_system"] }
wayland-client = { version = "0.31.11" }
wayland-protocols = { version = "0.32.9", features = ["client", "unstable"] }
wayland-protocols-wlr = { version = "0.3.8", features = ["client"] }
